// Zero-credit company directory + sector-aware proposal generator.
// No LLM, no API calls — everything runs on-device, so there are no
// integration credits or rate limits. Each company's proposal is tailored
// to what its sector actually cares about.

export const COMPANIES = [
  { name: "Mavin Records", sector: "Music Label", country: "Nigeria", website: "https://mavinrecords.com" },
  { name: "Chocolate City Music", sector: "Music Label", country: "Nigeria", website: "https://chocolatecitymusic.com" },
  { name: "YBNL Nation", sector: "Music Label", country: "Nigeria", website: "https://ybnlnation.com" },
  { name: "Starboy Entertainment", sector: "Music Label", country: "Nigeria", website: "https://starboy.com.ng" },
  { name: "DMW (Davido Music Worldwide)", sector: "Music Label", country: "Nigeria", website: "https://dmw.com" },
  { name: "Made Men Music Group", sector: "Music Label", country: "Nigeria", website: "https://mademenmusic.com" },
  { name: "Bankulli Entertainment", sector: "Music Label", country: "Nigeria", website: "https://bankulli.com" },
  { name: "Kennis Music", sector: "Music Label", country: "Nigeria", website: "https://kennismusic.com" },
  { name: "Empire Mates Entertainment (EME)", sector: "Music Label", country: "Nigeria", website: "https://eme.com.ng" },
  { name: "Hypertek Digital", sector: "Music Label", country: "Nigeria", website: "https://hypertek.com.ng" },
  { name: "Aristokrat Records", sector: "Music Label", country: "Nigeria", website: "https://aristokratrecords.com" },
  { name: "Jaguda Records", sector: "Music Label", country: "Nigeria", website: "https://jaguda.com" },
  { name: "DB Records", sector: "Music Label", country: "Nigeria", website: "https://dbrecords.com" },
  { name: "Spaceship Entertainment", sector: "Music Label", country: "Nigeria", website: "https://spaceship.com.ng" },
  { name: "Flytime Promotions", sector: "Music Promotion", country: "Nigeria", website: "https://flytime.com" },
  { name: "Tribe Music", sector: "Music Label", country: "Nigeria", website: "https://tribemusic.com" },
  { name: "Crown Troupe of Africa", sector: "Performing Arts", country: "Nigeria", website: "https://crowntroupe.com" },
  { name: "Nigerian Breweries", sector: "FMCG / Sponsorship", country: "Nigeria", website: "https://nigerianbreweriesplc.com" },
  { name: "Guinness Nigeria", sector: "FMCG / Sponsorship", country: "Nigeria", website: "https://guinness.com.ng" },
  { name: "Coca-Cola Nigeria", sector: "FMCG / Sponsorship", country: "Nigeria", website: "https://coca-cola.com.ng" },
  { name: "Pepsi Nigeria", sector: "FMCG / Sponsorship", country: "Nigeria", website: "https://pepsi.com.ng" },
  { name: "MTN Nigeria", sector: "Telecom", country: "Nigeria", website: "https://mtn.ng" },
  { name: "Airtel Nigeria", sector: "Telecom", country: "Nigeria", website: "https://airtel.com.ng" },
  { name: "Globacom", sector: "Telecom", country: "Nigeria", website: "https://gloworld.com" },
  { name: "9mobile", sector: "Telecom", country: "Nigeria", website: "https://9mobile.com.ng" },
  { name: "Dangote Group", sector: "Conglomerate / Investment", country: "Nigeria", website: "https://dangote.com" },
  { name: "BUA Group", sector: "Conglomerate / Investment", country: "Nigeria", website: "https://buagroup.com" },
  { name: "Tony Elumelu Foundation", sector: "Investment / Foundation", country: "Nigeria", website: "https://tonyelumelufoundation.org" },
  { name: "Lagos Angel Network", sector: "Investment", country: "Nigeria", website: "https://lagosangelnetwork.com" },
  { name: "Ventures Platform", sector: "Venture Capital", country: "Nigeria", website: "https://venturesplatform.com" },
  { name: "Greenhouse Capital", sector: "Venture Capital", country: "Nigeria", website: "https://greenhouse.capital" },
  { name: "EchoVC Partners", sector: "Venture Capital", country: "Nigeria", website: "https://echovc.com" },
  { name: "Microtraction", sector: "Venture Capital", country: "Nigeria", website: "https://microtraction.com" },
  { name: "Future Africa", sector: "Venture Capital", country: "Nigeria", website: "https://future.africa" },
  { name: "Lagos Innovates", sector: "Investment", country: "Nigeria", website: "https://lagosinnovates.com" },
  { name: "Nigerian Investment Promotion Commission", sector: "Government Investment", country: "Nigeria", website: "https://nipc.gov.ng" },
  { name: "Access Bank", sector: "Banking", country: "Nigeria", website: "https://accessbankplc.com" },
  { name: "Zenith Bank", sector: "Banking", country: "Nigeria", website: "https://zenithbank.com" },
  { name: "Guaranty Trust Bank", sector: "Banking", country: "Nigeria", website: "https://gtbank.com" },
  { name: "First Bank of Nigeria", sector: "Banking", country: "Nigeria", website: "https://firstbanknigeria.com" },
  { name: "United Bank for Africa", sector: "Banking", country: "Nigeria", website: "https://ubagroup.com" },
  { name: "Union Bank", sector: "Banking", country: "Nigeria", website: "https://unionbankng.com" },
  { name: "Fidelity Bank", sector: "Banking", country: "Nigeria", website: "https://fidelitybank.ng" },
  { name: "Stanbic IBTC", sector: "Banking", country: "Nigeria", website: "https://stanbicibtcbank.com" },
  { name: "Wema Bank", sector: "Banking", country: "Nigeria", website: "https://wemabank.com" },
  { name: "Sterling Bank", sector: "Banking", country: "Nigeria", website: "https://sterling.ng" },
  { name: "Polaris Bank", sector: "Banking", country: "Nigeria", website: "https://polarisbanklimited.com" },
  { name: "Keystone Bank", sector: "Banking", country: "Nigeria", website: "https://keystonebankng.com" },
  { name: "Jaiz Bank", sector: "Banking", country: "Nigeria", website: "https://jaizbankplc.com" },
  { name: "Providus Bank", sector: "Banking", country: "Nigeria", website: "https://providusbank.com" },
  { name: "SunTrust Bank", sector: "Banking", country: "Nigeria", website: "https://suntrustng.com" },
  { name: "FSDH Merchant Bank", sector: "Banking", country: "Nigeria", website: "https://fsdhgroup.com" },
  { name: "Rand Merchant Bank Nigeria", sector: "Investment Banking", country: "Nigeria", website: "https://rmb.com.ng" },
  { name: "Coronation Merchant Bank", sector: "Investment Banking", country: "Nigeria", website: "https://coronationmb.com" },
  { name: "Nova Merchant Bank", sector: "Investment Banking", country: "Nigeria", website: "https://novamb.com" },
  { name: "FBNQuest Merchant Bank", sector: "Investment Banking", country: "Nigeria", website: "https://fbnquest.com" },
  { name: "Chapel Hill Denham", sector: "Investment Banking", country: "Nigeria", website: "https://chapelhilldenham.com" },
  { name: "Vetiva Capital", sector: "Investment Banking", country: "Nigeria", website: "https://vetiva.com" },
  { name: "Afrinvest", sector: "Investment Banking", country: "Nigeria", website: "https://afrinvest.com" },
  { name: "Meristem Securities", sector: "Investment Banking", country: "Nigeria", website: "https://meristemng.com" },
  { name: "ARM Investment Managers", sector: "Investment", country: "Nigeria", website: "https://arm.com.ng" },
  { name: "United Capital", sector: "Investment Banking", country: "Nigeria", website: "https://unitedcapitalplcgroup.com" },
  { name: "AXA Mansard", sector: "Insurance / Investment", country: "Nigeria", website: "https://axamansard.com" },
  { name: "Leadway Assurance", sector: "Insurance", country: "Nigeria", website: "https://leadway.com" },
  { name: "AIICO Insurance", sector: "Insurance", country: "Nigeria", website: "https://aiicoplc.com" },
  { name: "Custodian Investment", sector: "Insurance / Investment", country: "Nigeria", website: "https://custodianplc.com" },
  { name: "FBN Insurance", sector: "Insurance", country: "Nigeria", website: "https://fbninsurance.com" },
  { name: "Seplat Energy", sector: "Oil & Gas", country: "Nigeria", website: "https://seplatenergy.com" },
  { name: "Oando PLC", sector: "Oil & Gas", country: "Nigeria", website: "https://oandoplc.com" },
  { name: "NNPC Limited", sector: "Oil & Gas", country: "Nigeria", website: "https://nnpcgroup.com" },
  { name: "Aiteo Group", sector: "Oil & Gas", country: "Nigeria", website: "https://aiteogroup.com" },
  { name: "Conoil PLC", sector: "Oil & Gas", country: "Nigeria", website: "https://conoilplc.com" },
  { name: "TotalEnergies Nigeria", sector: "Oil & Gas", country: "Nigeria", website: "https://totalenergies.ng" },
  { name: "Chevron Nigeria", sector: "Oil & Gas", country: "Nigeria", website: "https://nigeria.chevron.com" },
  { name: "Shell Nigeria", sector: "Oil & Gas", country: "Nigeria", website: "https://shell.com.ng" },
  { name: "ExxonMobil Nigeria", sector: "Oil & Gas", country: "Nigeria", website: "https://exxonmobil.com.ng" },
  { name: "Lagos State Employment Trust Fund", sector: "Government Funding", country: "Nigeria", website: "https://lsetf.ng" },
  { name: "Bank of Industry", sector: "Government Funding", country: "Nigeria", website: "https://boi.ng" },
  { name: "Nigeria Export-Import Bank (NEXIM)", sector: "Government Funding", country: "Nigeria", website: "https://neximbank.com.ng" },
  { name: "SMEDAN", sector: "Government", country: "Nigeria", website: "https://smedan.gov.ng" },
  { name: "Nigerian Content Development and Monitoring Board", sector: "Government", country: "Nigeria", website: "https://ncdmb.gov.ng" },
  { name: "Aliko Dangote Foundation", sector: "Foundation", country: "Nigeria", website: "https://dangote.com/foundation" },
  { name: "MTN Foundation", sector: "Foundation", country: "Nigeria", website: "https://mtn.ng/foundation" },
  { name: "Airtel Touching Lives", sector: "Foundation", country: "Nigeria", website: "https://airtel.com.ng/touchinglives" },
  { name: "Globacom Foundation", sector: "Foundation", country: "Nigeria", website: "https://gloworld.com/foundation" },
  { name: "First Bank Foundation", sector: "Foundation", country: "Nigeria", website: "https://firstbanknigeria.com/foundation" },
  { name: "Access Bank Foundation", sector: "Foundation", country: "Nigeria", website: "https://accessbankplc.com/foundation" },
  { name: "Zenith Bank Foundation", sector: "Foundation", country: "Nigeria", website: "https://zenithbank.com/foundation" },
  { name: "GTBank Foundation", sector: "Foundation", country: "Nigeria", website: "https://gtbank.com/foundation" },
  { name: "Flutterwave", sector: "Fintech", country: "Nigeria", website: "https://flutterwave.com" },
  { name: "Paystack", sector: "Fintech", country: "Nigeria", website: "https://paystack.com" },
  { name: "Interswitch", sector: "Fintech", country: "Nigeria", website: "https://interswitchgroup.com" },
  { name: "Paga", sector: "Fintech", country: "Nigeria", website: "https://paga.com" },
  { name: "Kuda Bank", sector: "Fintech", country: "Nigeria", website: "https://kuda.com" },
  { name: "PiggyVest", sector: "Fintech", country: "Nigeria", website: "https://piggyvest.com" },
  { name: "Cowrywise", sector: "Fintech", country: "Nigeria", website: "https://cowrywise.com" },
  { name: "Chipper Cash", sector: "Fintech", country: "Nigeria", website: "https://chippercash.com" },
  { name: "Moniepoint", sector: "Fintech", country: "Nigeria", website: "https://moniepoint.com" },
  { name: "OPay", sector: "Fintech", country: "Nigeria", website: "https://opay.ng" },
  { name: "PalmPay", sector: "Fintech", country: "Nigeria", website: "https://palmpay.com" },
  { name: "Andela", sector: "Tech Talent", country: "Nigeria", website: "https://andela.com" },
  { name: "Decagon", sector: "Tech Talent", country: "Nigeria", website: "https://decagonhq.com" },
  { name: "Semicolon Africa", sector: "Tech Talent", country: "Nigeria", website: "https://semicolon.africa" },
  { name: "Univelcity", sector: "Tech Training", country: "Nigeria", website: "https://univelcity.com" },
  { name: "Nithub", sector: "Tech Hub", country: "Nigeria", website: "https://nithub.unilag.edu.ng" },
  { name: "CcHub", sector: "Tech Hub", country: "Nigeria", website: "https://cchubnigeria.com" },
  { name: "Vatebra", sector: "Software", country: "Nigeria", website: "https://vatebra.com" },
  { name: "Sidmach Technologies", sector: "Software", country: "Nigeria", website: "https://sidmach.com" },
  { name: "Computer Warehouse Group", sector: "IT Services", country: "Nigeria", website: "https://cwlgroup.com" },
  { name: "Zinox Technologies", sector: "IT Hardware", country: "Nigeria", website: "https://zinoxtechnologies.com" },
  { name: "Channels Television", sector: "Media", country: "Nigeria", website: "https://channelstv.com" },
  { name: "Arise News", sector: "Media", country: "Nigeria", website: "https://arise.tv" },
  { name: "TV360 Nigeria", sector: "Media", country: "Nigeria", website: "https://tv360nigeria.com" },
  { name: "Africa Independent Television (AIT)", sector: "Media", country: "Nigeria", website: "https://ait.live" },
  { name: "Silverbird Group", sector: "Media / Entertainment", country: "Nigeria", website: "https://silverbirdgroup.com" },
  { name: "Filmhouse Cinemas", sector: "Entertainment", country: "Nigeria", website: "https://filmhouseng.com" },
  { name: "Genesis Cinemas", sector: "Entertainment", country: "Nigeria", website: "https://genesiscinemas.com" },
  { name: "Viva Cinemas", sector: "Entertainment", country: "Nigeria", website: "https://vivacinemas.com" },
  { name: "IrokoTV", sector: "Streaming", country: "Nigeria", website: "https://irokotv.com" },
  { name: "Netflix Nigeria", sector: "Streaming", country: "Nigeria", website: "https://netflix.com/ng" },
  { name: "Amazon Prime Video Nigeria", sector: "Streaming", country: "Nigeria", website: "https://primevideo.com" },
  { name: "Showmax Nigeria", sector: "Streaming", country: "Nigeria", website: "https://showmax.com" },
  { name: "MTN Music Plus", sector: "Music Streaming", country: "Nigeria", website: "https://mtnmusicsplus.com" },
  { name: "Boomplay", sector: "Music Streaming", country: "Nigeria", website: "https://boomplay.com" },
  { name: "Audiomack", sector: "Music Streaming", country: "Nigeria", website: "https://audiomack.com" },
  { name: "Spotify Nigeria", sector: "Music Streaming", country: "Nigeria", website: "https://spotify.com/ng" },
  { name: "Apple Music Nigeria", sector: "Music Streaming", country: "Nigeria", website: "https://apple.com/apple-music" },
  { name: "Nigeria LNG Limited", sector: "Energy", country: "Nigeria", website: "https://nlng.com" },
  { name: "Egbin Power", sector: "Energy", country: "Nigeria", website: "https://egbin-power.com" },
  { name: "Transcorp Power", sector: "Energy", country: "Nigeria", website: "https://transcorppower.com" },
  { name: "Sahara Group", sector: "Energy", country: "Nigeria", website: "https://sahara-group.com" },
  { name: "Aiteo Power", sector: "Energy", country: "Nigeria", website: "https://aiteopower.com" },
  { name: "Eko Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://ekedp.com" },
  { name: "Ikeja Electric", sector: "Utilities", country: "Nigeria", website: "https://ikejaelectric.com" },
  { name: "Abuja Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://abujaelectricity.com" },
  { name: "Kaduna Electric", sector: "Utilities", country: "Nigeria", website: "https://kadunaelectric.com" },
  { name: "Enugu Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://enugudisco.com" },
  { name: "Ibadan Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://ibedc.com" },
  { name: "Jos Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://jedplc.com" },
  { name: "Port Harcourt Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://phed.com.ng" },
  { name: "Yola Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://yedc.com.ng" },
  { name: "Kano Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://kedco.com" },
  { name: "Benin Electricity Distribution Company", sector: "Utilities", country: "Nigeria", website: "https://beninelectric.com" },
  { name: "Dangote Cement", sector: "Manufacturing", country: "Nigeria", website: "https://dangotecement.com" },
  { name: "BUA Cement", sector: "Manufacturing", country: "Nigeria", website: "https://buacement.com" },
  { name: "Lafarge Africa", sector: "Manufacturing", country: "Nigeria", website: "https://lafarge.com.ng" },
  { name: "Nestle Nigeria", sector: "FMCG", country: "Nigeria", website: "https://nestle.com.ng" },
  { name: "Unilever Nigeria", sector: "FMCG", country: "Nigeria", website: "https://unilevernigeria.com" },
  { name: "PZ Cussons Nigeria", sector: "FMCG", country: "Nigeria", website: "https://pzcussons.com" },
  { name: "Flour Mills of Nigeria", sector: "FMCG", country: "Nigeria", website: "https://fmnplc.com" },
  { name: "Honeywell Flour Mills", sector: "FMCG", country: "Nigeria", website: "https://honeywellflour.com" },
  { name: "De United Foods Industries", sector: "FMCG", country: "Nigeria", website: "https://dufil.com" },
  { name: "UAC of Nigeria", sector: "Conglomerate", country: "Nigeria", website: "https://uacnplc.com" },
  { name: "Chemical and Allied Products (CAP)", sector: "FMCG", country: "Nigeria", website: "https://capplc.com" },
  { name: "FrieslandCampina WAMCO", sector: "FMCG", country: "Nigeria", website: "https://frieslandcampina.com.ng" },
  { name: "Promasidor Nigeria", sector: "FMCG", country: "Nigeria", website: "https://promasidor.com" },
  { name: "Nigerian Bottling Company", sector: "Beverages", country: "Nigeria", website: "https://nigerianbottlingcompany.com" },
  { name: "International Breweries", sector: "Beverages", country: "Nigeria", website: "https://internationalbreweriesplc.com" },
  { name: "Champion Breweries", sector: "Beverages", country: "Nigeria", website: "https://championbrew.com" },
  { name: "McDonalds Nigeria", sector: "QSR", country: "Nigeria", website: "https://mcdonalds.com.ng" },
  { name: "Chicken Republic", sector: "QSR", country: "Nigeria", website: "https://chicken-republic.com" },
  { name: "Domino's Pizza Nigeria", sector: "QSR", country: "Nigeria", website: "https://dominos.com.ng" },
  { name: "Cold Stone Creamery Nigeria", sector: "QSR", country: "Nigeria", website: "https://coldstonecreamery.com.ng" },
  { name: "KFC Nigeria", sector: "QSR", country: "Nigeria", website: "https://kfc.com.ng" },
  { name: "Mr Bigg's", sector: "QSR", country: "Nigeria", website: "https://mrbiggs.com.ng" },
  { name: "Sweet Sensation", sector: "QSR", country: "Nigeria", website: "https://sweetsensation.com.ng" },
  { name: "Tantalizers", sector: "QSR", country: "Nigeria", website: "https://tantalizersng.com" },
  { name: "The Place Nigeria", sector: "QSR", country: "Nigeria", website: "https://theplace.com.ng" },
  { name: "Mega Chicken", sector: "QSR", country: "Nigeria", website: "https://megachicken.com" },
  { name: "Eat 'N' Go", sector: "QSR", country: "Nigeria", website: "https://eatngo.com" },
  { name: "Jumia Nigeria", sector: "E-commerce", country: "Nigeria", website: "https://jumia.com.ng" },
  { name: "Konga", sector: "E-commerce", country: "Nigeria", website: "https://konga.com" },
  { name: "Slot Nigeria", sector: "Retail", country: "Nigeria", website: "https://slot.ng" },
  { name: "Pointek", sector: "Retail", country: "Nigeria", website: "https://pointekonline.com" },
  { name: "Game Stores Nigeria", sector: "Retail", country: "Nigeria", website: "https://game.co.za/ng" },
  { name: "Shoprite Nigeria", sector: "Retail", country: "Nigeria", website: "https://shoprite.com.ng" },
  { name: "SPAR Nigeria", sector: "Retail", country: "Nigeria", website: "https://spar.ng" },
  { name: "Hubmart", sector: "Retail", country: "Nigeria", website: "https://hubmart.com" },
  { name: "Ebeano Supermarket", sector: "Retail", country: "Nigeria", website: "https://ebeano.com" },
  { name: "Justrite Superstore", sector: "Retail", country: "Nigeria", website: "https://justrite.com" },
  { name: "MedPlus Pharmacy", sector: "Healthcare", country: "Nigeria", website: "https://medplusng.com" },
  { name: "HealthPlus Pharmacy", sector: "Healthcare", country: "Nigeria", website: "https://healthplus.com.ng" },
  { name: "Nett Pharmacy", sector: "Healthcare", country: "Nigeria", website: "https://nettpharmacy.com" },
  { name: "Fidson Healthcare", sector: "Pharmaceutical", country: "Nigeria", website: "https://fidson.com" },
  { name: "May & Baker Nigeria", sector: "Pharmaceutical", country: "Nigeria", website: "https://may-baker.com" },
  { name: "GlaxoSmithKline Nigeria", sector: "Pharmaceutical", country: "Nigeria", website: "https://gsk.com.ng" },
  { name: "Emzor Pharmaceuticals", sector: "Pharmaceutical", country: "Nigeria", website: "https://emzorpharma.com" },
  { name: "Swiss Biostadt", sector: "Pharmaceutical", country: "Nigeria", website: "https://swissbiostadt.com" },
  { name: "Chi Limited", sector: "FMCG", country: "Nigeria", website: "https://chilimited.com" },
  { name: "Dangote Sugar Refinery", sector: "Manufacturing", country: "Nigeria", website: "https://dangotesugar.com" },
  { name: "BUA Sugar", sector: "Manufacturing", country: "Nigeria", website: "https://buasugar.com" },
  { name: "Golden Penny", sector: "FMCG", country: "Nigeria", website: "https://goldenpenny.com.ng" },
  { name: "Honeywell Group", sector: "Conglomerate", country: "Nigeria", website: "https://honeywellgroup.com" },
  { name: "SIFAX Group", sector: "Logistics", country: "Nigeria", website: "https://sifaxgroup.com" },
  { name: "DHL Nigeria", sector: "Logistics", country: "Nigeria", website: "https://dhl.com/ng" },
  { name: "FedEx Nigeria", sector: "Logistics", country: "Nigeria", website: "https://fedex.com/ng" },
  { name: "GIG Logistics", sector: "Logistics", country: "Nigeria", website: "https://giglogistics.com" },
  { name: "Sendbox", sector: "Logistics", country: "Nigeria", website: "https://sendbox.ng" },
  { name: "Kobo360", sector: "Logistics", country: "Nigeria", website: "https://kobo360.com" },
  { name: "Max.ng", sector: "Mobility", country: "Nigeria", website: "https://max.ng" },
  { name: "Gokada", sector: "Mobility", country: "Nigeria", website: "https://gokada.com" },
  { name: "Opay Ride", sector: "Mobility", country: "Nigeria", website: "https://opay.ng/ride" },
  { name: "Bolt Nigeria", sector: "Mobility", country: "Nigeria", website: "https://bolt.eu/ng" },
  { name: "Uber Nigeria", sector: "Mobility", country: "Nigeria", website: "https://uber.com/ng" },
  { name: "Lori Systems", sector: "Logistics", country: "Nigeria", website: "https://lorisystems.com" },
  { name: "Kwik Delivery", sector: "Logistics", country: "Nigeria", website: "https://kwik.ng" },
  { name: "Air Peace", sector: "Aviation", country: "Nigeria", website: "https://flyairpeace.com" },
  { name: "Arik Air", sector: "Aviation", country: "Nigeria", website: "https://arikair.com" },
  { name: "Dana Air", sector: "Aviation", country: "Nigeria", website: "https://flydanaair.com" },
  { name: "Green Africa Airways", sector: "Aviation", country: "Nigeria", website: "https://greenafrica.com" },
  { name: "Ibom Air", sector: "Aviation", country: "Nigeria", website: "https://ibomair.com" },
  { name: "Overland Airways", sector: "Aviation", country: "Nigeria", website: "https://overlandairways.com" },
  { name: "Aero Contractors", sector: "Aviation", country: "Nigeria", website: "https://aacontractors.com" },
  { name: "Max Air", sector: "Aviation", country: "Nigeria", website: "https://maxair.com.ng" },
  { name: "Azman Air", sector: "Aviation", country: "Nigeria", website: "https://azmanair.com" },
  { name: "United Nigeria Airlines", sector: "Aviation", country: "Nigeria", website: "https://flyunitednigeria.com" },
  { name: "Apple Inc.", sector: "Technology", country: "USA", website: "https://apple.com" },
  { name: "Google", sector: "Technology", country: "USA", website: "https://google.com" },
  { name: "Microsoft", sector: "Technology", country: "USA", website: "https://microsoft.com" },
  { name: "Amazon", sector: "E-commerce / Cloud", country: "USA", website: "https://amazon.com" },
  { name: "Meta (Facebook)", sector: "Social Media", country: "USA", website: "https://meta.com" },
  { name: "Tesla", sector: "Automotive / Energy", country: "USA", website: "https://tesla.com" },
  { name: "Netflix", sector: "Streaming", country: "USA", website: "https://netflix.com" },
  { name: "Twitter (X)", sector: "Social Media", country: "USA", website: "https://twitter.com" },
  { name: "LinkedIn", sector: "Social Media", country: "USA", website: "https://linkedin.com" },
  { name: "Airbnb", sector: "Travel", country: "USA", website: "https://airbnb.com" },
  { name: "Uber", sector: "Mobility", country: "USA", website: "https://uber.com" },
  { name: "Lyft", sector: "Mobility", country: "USA", website: "https://lyft.com" },
  { name: "SpaceX", sector: "Aerospace", country: "USA", website: "https://spacex.com" },
  { name: "IBM", sector: "Technology", country: "USA", website: "https://ibm.com" },
  { name: "Intel", sector: "Semiconductors", country: "USA", website: "https://intel.com" },
  { name: "AMD", sector: "Semiconductors", country: "USA", website: "https://amd.com" },
  { name: "NVIDIA", sector: "Semiconductors", country: "USA", website: "https://nvidia.com" },
  { name: "Adobe", sector: "Software", country: "USA", website: "https://adobe.com" },
  { name: "Salesforce", sector: "Software", country: "USA", website: "https://salesforce.com" },
  { name: "Oracle", sector: "Software", country: "USA", website: "https://oracle.com" },
  { name: "Cisco", sector: "Networking", country: "USA", website: "https://cisco.com" },
  { name: "PayPal", sector: "Fintech", country: "USA", website: "https://paypal.com" },
  { name: "Stripe", sector: "Fintech", country: "USA", website: "https://stripe.com" },
  { name: "Square (Block)", sector: "Fintech", country: "USA", website: "https://block.xyz" },
  { name: "Coinbase", sector: "Cryptocurrency", country: "USA", website: "https://coinbase.com" },
  { name: "OpenAI", sector: "Artificial Intelligence", country: "USA", website: "https://openai.com" },
  { name: "Anthropic", sector: "Artificial Intelligence", country: "USA", website: "https://anthropic.com" },
  { name: "DeepMind", sector: "Artificial Intelligence", country: "USA", website: "https://deepmind.com" },
  { name: "NASA", sector: "Space Agency", country: "USA", website: "https://nasa.gov" },
  { name: "Ford", sector: "Automotive", country: "USA", website: "https://ford.com" },
  { name: "General Motors", sector: "Automotive", country: "USA", website: "https://gm.com" },
  { name: "Boeing", sector: "Aerospace", country: "USA", website: "https://boeing.com" },
  { name: "Lockheed Martin", sector: "Defense", country: "USA", website: "https://lockheedmartin.com" },
  { name: "Raytheon", sector: "Defense", country: "USA", website: "https://rtx.com" },
  { name: "McDonald's", sector: "QSR", country: "USA", website: "https://mcdonalds.com" },
  { name: "Starbucks", sector: "QSR", country: "USA", website: "https://starbucks.com" },
  { name: "Coca-Cola", sector: "Beverages", country: "USA", website: "https://coca-cola.com" },
  { name: "PepsiCo", sector: "Beverages", country: "USA", website: "https://pepsico.com" },
  { name: "Procter & Gamble", sector: "FMCG", country: "USA", website: "https://pg.com" },
  { name: "Johnson & Johnson", sector: "Healthcare", country: "USA", website: "https://jnj.com" },
  { name: "Pfizer", sector: "Pharmaceutical", country: "USA", website: "https://pfizer.com" },
  { name: "Moderna", sector: "Biotech", country: "USA", website: "https://modernatx.com" },
  { name: "Walmart", sector: "Retail", country: "USA", website: "https://walmart.com" },
  { name: "Target", sector: "Retail", country: "USA", website: "https://target.com" },
  { name: "Costco", sector: "Retail", country: "USA", website: "https://costco.com" },
  { name: "Home Depot", sector: "Retail", country: "USA", website: "https://homedepot.com" },
  { name: "Best Buy", sector: "Retail", country: "USA", website: "https://bestbuy.com" },
  { name: "Nike", sector: "Apparel", country: "USA", website: "https://nike.com" },
  { name: "Under Armour", sector: "Apparel", country: "USA", website: "https://underarmour.com" },
  { name: "Disney", sector: "Entertainment", country: "USA", website: "https://disney.com" },
  { name: "Warner Bros. Discovery", sector: "Entertainment", country: "USA", website: "https://wbd.com" },
  { name: "Universal Music Group", sector: "Music Label", country: "USA", website: "https://umusic.com" },
  { name: "Sony Music", sector: "Music Label", country: "USA", website: "https://sonymusic.com" },
  { name: "Warner Music Group", sector: "Music Label", country: "USA", website: "https://wmg.com" },
  { name: "Spotify", sector: "Music Streaming", country: "USA", website: "https://spotify.com" },
  { name: "Apple Music", sector: "Music Streaming", country: "USA", website: "https://apple.com/apple-music" },
  { name: "Pandora", sector: "Music Streaming", country: "USA", website: "https://pandora.com" },
  { name: "SoundCloud", sector: "Music Streaming", country: "USA", website: "https://soundcloud.com" },
  { name: "TikTok", sector: "Social Media", country: "USA", website: "https://tiktok.com" },
  { name: "Snap Inc.", sector: "Social Media", country: "USA", website: "https://snap.com" },
  { name: "Pinterest", sector: "Social Media", country: "USA", website: "https://pinterest.com" },
  { name: "Reddit", sector: "Social Media", country: "USA", website: "https://reddit.com" },
  { name: "Expedia", sector: "Travel", country: "USA", website: "https://expedia.com" },
  { name: "Booking.com", sector: "Travel", country: "USA", website: "https://booking.com" },
  { name: "TripAdvisor", sector: "Travel", country: "USA", website: "https://tripadvisor.com" },
  { name: "Marriott", sector: "Hotels", country: "USA", website: "https://marriott.com" },
  { name: "Hilton", sector: "Hotels", country: "USA", website: "https://hilton.com" },
  { name: "Hyatt", sector: "Hotels", country: "USA", website: "https://hyatt.com" },
  { name: "American Express", sector: "Finance", country: "USA", website: "https://americanexpress.com" },
  { name: "Visa", sector: "Finance", country: "USA", website: "https://visa.com" },
  { name: "Mastercard", sector: "Finance", country: "USA", website: "https://mastercard.com" },
  { name: "Goldman Sachs", sector: "Investment Banking", country: "USA", website: "https://goldmansachs.com" },
  { name: "Morgan Stanley", sector: "Investment Banking", country: "USA", website: "https://morganstanley.com" },
  { name: "JPMorgan Chase", sector: "Banking", country: "USA", website: "https://jpmorganchase.com" },
  { name: "Bank of America", sector: "Banking", country: "USA", website: "https://bankofamerica.com" },
  { name: "Wells Fargo", sector: "Banking", country: "USA", website: "https://wellsfargo.com" },
  { name: "Citigroup", sector: "Banking", country: "USA", website: "https://citigroup.com" },
  { name: "BlackRock", sector: "Asset Management", country: "USA", website: "https://blackrock.com" },
  { name: "Vanguard", sector: "Asset Management", country: "USA", website: "https://vanguard.com" },
  { name: "Fidelity", sector: "Asset Management", country: "USA", website: "https://fidelity.com" },
  { name: "Charles Schwab", sector: "Finance", country: "USA", website: "https://schwab.com" },
  { name: "Robinhood", sector: "Fintech", country: "USA", website: "https://robinhood.com" },
  { name: "DoorDash", sector: "Food Delivery", country: "USA", website: "https://doordash.com" },
  { name: "Grubhub", sector: "Food Delivery", country: "USA", website: "https://grubhub.com" },
  { name: "Instacart", sector: "Grocery Delivery", country: "USA", website: "https://instacart.com" },
  { name: "T-Mobile", sector: "Telecom", country: "USA", website: "https://t-mobile.com" },
  { name: "Verizon", sector: "Telecom", country: "USA", website: "https://verizon.com" },
  { name: "AT&T", sector: "Telecom", country: "USA", website: "https://att.com" },
  { name: "Comcast", sector: "Telecom", country: "USA", website: "https://comcast.com" },
  { name: "Charter Communications", sector: "Telecom", country: "USA", website: "https://spectrum.com" },
  { name: "Liberty Global", sector: "Telecom", country: "USA", website: "https://libertyglobal.com" },
  { name: "Accenture", sector: "Consulting", country: "USA", website: "https://accenture.com" },
  { name: "Deloitte", sector: "Consulting", country: "USA", website: "https://deloitte.com" },
  { name: "PwC", sector: "Consulting", country: "USA", website: "https://pwc.com" },
  { name: "Ernst & Young", sector: "Consulting", country: "USA", website: "https://ey.com" },
  { name: "KPMG", sector: "Consulting", country: "USA", website: "https://kpmg.com" },
  { name: "McKinsey & Company", sector: "Consulting", country: "USA", website: "https://mckinsey.com" },
  { name: "Boston Consulting Group", sector: "Consulting", country: "USA", website: "https://bcg.com" },
  { name: "Bain & Company", sector: "Consulting", country: "USA", website: "https://bain.com" },
  { name: "Vodafone", sector: "Telecom", country: "UK", website: "https://vodafone.com" },
  { name: "BT Group", sector: "Telecom", country: "UK", website: "https://bt.com" },
  { name: "Three UK", sector: "Telecom", country: "UK", website: "https://three.co.uk" },
  { name: "O2 UK", sector: "Telecom", country: "UK", website: "https://o2.co.uk" },
  { name: "Sky", sector: "Media / Telecom", country: "UK", website: "https://sky.com" },
  { name: "BBC", sector: "Media", country: "UK", website: "https://bbc.co.uk" },
  { name: "ITV", sector: "Media", country: "UK", website: "https://itv.com" },
  { name: "Channel 4", sector: "Media", country: "UK", website: "https://channel4.com" },
  { name: "British Airways", sector: "Aviation", country: "UK", website: "https://ba.com" },
  { name: "Virgin Atlantic", sector: "Aviation", country: "UK", website: "https://virginatlantic.com" },
  { name: "Rolls-Royce", sector: "Aerospace", country: "UK", website: "https://rolls-royce.com" },
  { name: "BAE Systems", sector: "Defense", country: "UK", website: "https://baesystems.com" },
  { name: "HSBC", sector: "Banking", country: "UK", website: "https://hsbc.com" },
  { name: "Barclays", sector: "Banking", country: "UK", website: "https://barclays.com" },
  { name: "Lloyds Banking Group", sector: "Banking", country: "UK", website: "https://lloydsbankinggroup.com" },
  { name: "Royal Bank of Scotland", sector: "Banking", country: "UK", website: "https://rbs.com" },
  { name: "Standard Chartered", sector: "Banking", country: "UK", website: "https://sc.com" },
  { name: "Prudential", sector: "Insurance", country: "UK", website: "https://prudential.co.uk" },
  { name: "Aviva", sector: "Insurance", country: "UK", website: "https://aviva.com" },
  { name: "Legal & General", sector: "Insurance", country: "UK", website: "https://legalandgeneral.com" },
  { name: "Unilever", sector: "FMCG", country: "UK", website: "https://unilever.com" },
  { name: "Diageo", sector: "Beverages", country: "UK", website: "https://diageo.com" },
  { name: "AstraZeneca", sector: "Pharmaceutical", country: "UK", website: "https://astrazeneca.com" },
  { name: "British Petroleum (BP)", sector: "Oil & Gas", country: "UK", website: "https://bp.com" },
  { name: "Shell", sector: "Oil & Gas", country: "UK", website: "https://shell.com" },
  { name: "Sainsbury's", sector: "Retail", country: "UK", website: "https://sainsburys.co.uk" },
  { name: "Tesco", sector: "Retail", country: "UK", website: "https://tesco.com" },
  { name: "Marks & Spencer", sector: "Retail", country: "UK", website: "https://marksandspencer.com" },
  { name: "ASOS", sector: "E-commerce", country: "UK", website: "https://asos.com" },
  { name: "Royal Mail", sector: "Logistics", country: "UK", website: "https://royalmail.com" },
  { name: "Siemens", sector: "Engineering", country: "Germany", website: "https://siemens.com" },
  { name: "Volkswagen", sector: "Automotive", country: "Germany", website: "https://volkswagen.com" },
  { name: "BMW", sector: "Automotive", country: "Germany", website: "https://bmw.com" },
  { name: "Mercedes-Benz", sector: "Automotive", country: "Germany", website: "https://mercedes-benz.com" },
  { name: "Audi", sector: "Automotive", country: "Germany", website: "https://audi.com" },
  { name: "Bosch", sector: "Engineering", country: "Germany", website: "https://bosch.com" },
  { name: "Adidas", sector: "Apparel", country: "Germany", website: "https://adidas.com" },
  { name: "Puma", sector: "Apparel", country: "Germany", website: "https://puma.com" },
  { name: "SAP", sector: "Software", country: "Germany", website: "https://sap.com" },
  { name: "Deutsche Bank", sector: "Banking", country: "Germany", website: "https://deutsche-bank.com" },
  { name: "Allianz", sector: "Insurance", country: "Germany", website: "https://allianz.com" },
  { name: "BASF", sector: "Chemicals", country: "Germany", website: "https://basf.com" },
  { name: "Bayer", sector: "Pharmaceutical", country: "Germany", website: "https://bayer.com" },
  { name: "Siemens Healthineers", sector: "Healthcare", country: "Germany", website: "https://siemens-healthineers.com" },
  { name: "Lufthansa", sector: "Aviation", country: "Germany", website: "https://lufthansa.com" },
  { name: "Deutsche Telekom", sector: "Telecom", country: "Germany", website: "https://telekom.com" },
  { name: "Zalando", sector: "E-commerce", country: "Germany", website: "https://zalando.com" },
  { name: "HelloFresh", sector: "Food Delivery", country: "Germany", website: "https://hellofresh.com" },
  { name: "Nestlé", sector: "FMCG", country: "Switzerland", website: "https://nestle.com" },
  { name: "Novartis", sector: "Pharmaceutical", country: "Switzerland", website: "https://novartis.com" },
  { name: "Roche", sector: "Pharmaceutical", country: "Switzerland", website: "https://roche.com" },
  { name: "UBS", sector: "Banking", country: "Switzerland", website: "https://ubs.com" },
  { name: "Credit Suisse", sector: "Banking", country: "Switzerland", website: "https://credit-suisse.com" },
  { name: "Swiss Re", sector: "Insurance", country: "Switzerland", website: "https://swissre.com" },
  { name: "Zurich Insurance", sector: "Insurance", country: "Switzerland", website: "https://zurich.com" },
  { name: "Rolex", sector: "Luxury", country: "Switzerland", website: "https://rolex.com" },
  { name: "Swatch Group", sector: "Luxury", country: "Switzerland", website: "https://swatchgroup.com" },
  { name: "ABB", sector: "Engineering", country: "Switzerland", website: "https://abb.com" },
  { name: "Adecco", sector: "HR", country: "Switzerland", website: "https://adecco.com" },
  { name: "Tata Group", sector: "Conglomerate", country: "India", website: "https://tata.com" },
  { name: "Reliance Industries", sector: "Conglomerate", country: "India", website: "https://ril.com" },
  { name: "Infosys", sector: "Technology", country: "India", website: "https://infosys.com" },
  { name: "Wipro", sector: "Technology", country: "India", website: "https://wipro.com" },
  { name: "HCL Technologies", sector: "Technology", country: "India", website: "https://hcltech.com" },
  { name: "Tech Mahindra", sector: "Technology", country: "India", website: "https://techmahindra.com" },
  { name: "Bharti Airtel", sector: "Telecom", country: "India", website: "https://airtel.in" },
  { name: "Reliance Jio", sector: "Telecom", country: "India", website: "https://jio.com" },
  { name: "Flipkart", sector: "E-commerce", country: "India", website: "https://flipkart.com" },
  { name: "Paytm", sector: "Fintech", country: "India", website: "https://paytm.com" },
  { name: "Ola", sector: "Mobility", country: "India", website: "https://ola.com" },
  { name: "Swiggy", sector: "Food Delivery", country: "India", website: "https://swiggy.com" },
  { name: "Zomato", sector: "Food Delivery", country: "India", website: "https://zomato.com" },
  { name: "Byju's", sector: "EdTech", country: "India", website: "https://byjus.com" },
  { name: "Unacademy", sector: "EdTech", country: "India", website: "https://unacademy.com" },
  { name: "Dream11", sector: "Gaming", country: "India", website: "https://dream11.com" },
  { name: "OYO Rooms", sector: "Hotels", country: "India", website: "https://oyorooms.com" },
  { name: "MakeMyTrip", sector: "Travel", country: "India", website: "https://makemytrip.com" },
  { name: "BookMyShow", sector: "Entertainment", country: "India", website: "https://bookmyshow.com" },
  { name: "Emirates", sector: "Aviation", country: "UAE", website: "https://emirates.com" },
  { name: "Etihad Airways", sector: "Aviation", country: "UAE", website: "https://etihad.com" },
  { name: "Qatar Airways", sector: "Aviation", country: "Qatar", website: "https://qatarairways.com" },
  { name: "Saudi Aramco", sector: "Oil & Gas", country: "Saudi Arabia", website: "https://aramco.com" },
  { name: "SABIC", sector: "Chemicals", country: "Saudi Arabia", website: "https://sabic.com" },
  { name: "Alibaba", sector: "E-commerce", country: "China", website: "https://alibaba.com" },
  { name: "Tencent", sector: "Technology", country: "China", website: "https://tencent.com" },
  { name: "Baidu", sector: "Technology", country: "China", website: "https://baidu.com" },
  { name: "Huawei", sector: "Technology", country: "China", website: "https://huawei.com" },
  { name: "Xiaomi", sector: "Technology", country: "China", website: "https://xiaomi.com" },
  { name: "Lenovo", sector: "Technology", country: "China", website: "https://lenovo.com" },
  { name: "DJI", sector: "Drones", country: "China", website: "https://dji.com" },
  { name: "BYD", sector: "Automotive", country: "China", website: "https://byd.com" },
  { name: "Geely", sector: "Automotive", country: "China", website: "https://geely.com" },
  { name: "Samsung", sector: "Technology", country: "South Korea", website: "https://samsung.com" },
  { name: "LG Electronics", sector: "Technology", country: "South Korea", website: "https://lg.com" },
  { name: "Hyundai", sector: "Automotive", country: "South Korea", website: "https://hyundai.com" },
  { name: "Kia", sector: "Automotive", country: "South Korea", website: "https://kia.com" },
  { name: "SK Group", sector: "Conglomerate", country: "South Korea", website: "https://sk.com" },
  { name: "Sony", sector: "Technology", country: "Japan", website: "https://sony.com" },
  { name: "Toyota", sector: "Automotive", country: "Japan", website: "https://toyota.com" },
  { name: "Honda", sector: "Automotive", country: "Japan", website: "https://honda.com" },
  { name: "Nissan", sector: "Automotive", country: "Japan", website: "https://nissan-global.com" },
  { name: "Panasonic", sector: "Technology", country: "Japan", website: "https://panasonic.com" },
  { name: "Mitsubishi", sector: "Conglomerate", country: "Japan", website: "https://mitsubishi.com" },
  { name: "SoftBank", sector: "Investment", country: "Japan", website: "https://softbank.com" },
  { name: "Rakuten", sector: "E-commerce", country: "Japan", website: "https://rakuten.com" },
  { name: "Canon", sector: "Technology", country: "Japan", website: "https://canon.com" },
  { name: "Nintendo", sector: "Gaming", country: "Japan", website: "https://nintendo.com" },
  { name: "Sega", sector: "Gaming", country: "Japan", website: "https://sega.com" },
  { name: "Bandai Namco", sector: "Gaming", country: "Japan", website: "https://bandainamco.com" },
  { name: "Capcom", sector: "Gaming", country: "Japan", website: "https://capcom.com" },
  { name: "Square Enix", sector: "Gaming", country: "Japan", website: "https://square-enix.com" },
  { name: "Konami", sector: "Gaming", country: "Japan", website: "https://konami.com" },
  { name: "Kakao", sector: "Technology", country: "South Korea", website: "https://kakao.com" },
  { name: "Naver", sector: "Technology", country: "South Korea", website: "https://naver.com" },
  { name: "Coupang", sector: "E-commerce", country: "South Korea", website: "https://coupang.com" },
  { name: "Lotte", sector: "Conglomerate", country: "South Korea", website: "https://lotte.com" },
  { name: "Posco", sector: "Steel", country: "South Korea", website: "https://posco.com" },
  { name: "Shinhan Bank", sector: "Banking", country: "South Korea", website: "https://shinhan.com" },
  { name: "KB Financial Group", sector: "Banking", country: "South Korea", website: "https://kbfg.com" },
  { name: "Mitsubishi UFJ Financial Group", sector: "Banking", country: "Japan", website: "https://mufg.jp" },
  { name: "Sumitomo Mitsui Banking", sector: "Banking", country: "Japan", website: "https://smbc.co.jp" },
  { name: "Mizuho Financial Group", sector: "Banking", country: "Japan", website: "https://mizuho-fg.co.jp" },
  { name: "Nomura Holdings", sector: "Finance", country: "Japan", website: "https://nomura.com" },
  { name: "Daiwa Securities", sector: "Finance", country: "Japan", website: "https://daiwa.jp" },
  { name: "Sony Music Japan", sector: "Music Label", country: "Japan", website: "https://sonymusic.co.jp" },
  { name: "Avex Group", sector: "Music Label", country: "Japan", website: "https://avex.com" },
  { name: "JYP Entertainment", sector: "Music Label", country: "South Korea", website: "https://jype.com" },
  { name: "SM Entertainment", sector: "Music Label", country: "South Korea", website: "https://smentertainment.com" },
  { name: "YG Entertainment", sector: "Music Label", country: "South Korea", website: "https://ygfamily.com" },
  { name: "HYBE", sector: "Music Label", country: "South Korea", website: "https://hybecorp.com" },
  { name: "Universal Music Canada", sector: "Music Label", country: "Canada", website: "https://umusic.ca" },
  { name: "Sony Music Canada", sector: "Music Label", country: "Canada", website: "https://sonymusic.ca" },
  { name: "Warner Music Canada", sector: "Music Label", country: "Canada", website: "https://warnermusic.ca" },
  { name: "Cirque du Soleil", sector: "Entertainment", country: "Canada", website: "https://cirquedusoleil.com" },
  { name: "Shopify", sector: "E-commerce", country: "Canada", website: "https://shopify.com" },
  { name: "TD Bank", sector: "Banking", country: "Canada", website: "https://td.com" },
  { name: "Royal Bank of Canada", sector: "Banking", country: "Canada", website: "https://rbc.com" },
  { name: "Scotiabank", sector: "Banking", country: "Canada", website: "https://scotiabank.com" },
  { name: "BMO", sector: "Banking", country: "Canada", website: "https://bmo.com" },
  { name: "CIBC", sector: "Banking", country: "Canada", website: "https://cibc.com" },
  { name: "Air Canada", sector: "Aviation", country: "Canada", website: "https://aircanada.com" },
  { name: "WestJet", sector: "Aviation", country: "Canada", website: "https://westjet.com" },
  { name: "Bombardier", sector: "Aerospace", country: "Canada", website: "https://bombardier.com" },
  { name: "Magna International", sector: "Automotive", country: "Canada", website: "https://magna.com" },
  { name: "Sun Life Financial", sector: "Insurance", country: "Canada", website: "https://sunlife.com" },
  { name: "Manulife", sector: "Insurance", country: "Canada", website: "https://manulife.com" },
  { name: "Enbridge", sector: "Energy", country: "Canada", website: "https://enbridge.com" },
  { name: "Canadian Natural Resources", sector: "Oil & Gas", country: "Canada", website: "https://cnrl.com" },
  { name: "Suncor Energy", sector: "Oil & Gas", country: "Canada", website: "https://suncor.com" },
  { name: "Nutrien", sector: "Agriculture", country: "Canada", website: "https://nutrien.com" },
  { name: "Loblaw", sector: "Retail", country: "Canada", website: "https://loblaw.ca" },
  { name: "Canadian Tire", sector: "Retail", country: "Canada", website: "https://canadiantire.ca" },
  { name: "Bell Canada", sector: "Telecom", country: "Canada", website: "https://bell.ca" },
  { name: "Rogers Communications", sector: "Telecom", country: "Canada", website: "https://rogers.com" },
  { name: "Telus", sector: "Telecom", country: "Canada", website: "https://telus.com" },
  { name: "Tim Hortons", sector: "QSR", country: "Canada", website: "https://timhortons.com" },
  { name: "Maple Leaf Foods", sector: "FMCG", country: "Canada", website: "https://mapleleaffoods.com" },
  { name: "Saputo", sector: "FMCG", country: "Canada", website: "https://saputo.com" },
];

export const COUNTRIES = [...new Set(COMPANIES.map((c) => c.country))].sort();

// What each sector cares about → how Ride X serves that interest + the ask.
export function sectorAngle(sector = "") {
  const s = sector.toLowerCase();
  if (s.includes("music") || s.includes("performing"))
    return { interest: "artist development, chart-topping releases, and cultural moments that move streaming numbers", offer: "Ride X places your artists in front of an engaged African audience through in-app premieres, playlist boosting, concert ticketing, and sponsored live events — accelerating streams, ticket sales, and brand reach.", ask: "a joint release-campaign and live-show partnership" };
  if (s.includes("bank") || s.includes("finance") || s.includes("invest") || s.includes("asset") || s.includes("insurance"))
    return { interest: "customer acquisition, transaction volume, and trusted brand presence with high-intent consumers", offer: "Ride X's millions of active lifestyle users are a high-intent payments audience. A co-branded card, wallet integration, or financial-services embed can drive sign-ups and daily transactions at low CAC.", ask: "a co-branded financial product or customer-acquisition sponsorship" };
  if (s.includes("telecom"))
    return { interest: "data usage growth, subscriber retention, and youth-relevant brand association", offer: "Ride X's streaming, gaming, and ride-hail features are heavy data consumers. A bundled data plan or Ride X reward partnership can lift ARPU and reduce churn across your subscriber base.", ask: "a data-bundle and rewards co-marketing partnership" };
  if (s.includes("oil") || s.includes("energy") || s.includes("utilities"))
    return { interest: "workforce logistics, community CSR, and brand visibility with energy consumers", offer: "Ride X's logistics and equipment-rental arms can support your field operations, while sponsored ride-hail and delivery campaigns reach energy consumers at the household level.", ask: "a logistics and CSR-branding partnership" };
  if (s.includes("fmcg") || s.includes("beverage") || s.includes("qsr") || s.includes("retail") || s.includes("food") || s.includes("agricultur"))
    return { interest: "product trial, top-of-mind awareness, and point-of-purchase conversion", offer: "Ride X's in-app ads, reward redemptions, and sponsored ride/delivery promotions put your product in front of consumers at the moment of intent — driving trial and repeat purchase.", ask: "a product-sampling and in-app rewards sponsorship" };
  if (s.includes("pharma") || s.includes("health"))
    return { interest: "patient access, trusted health communication, and community wellness reach", offer: "Ride X's large African user base and delivery logistics can support medicine-access programs and verified health-information campaigns at scale.", ask: "a health-access and wellness-information partnership" };
  if (s.includes("aviation") || s.includes("aerospace") || s.includes("airline"))
    return { interest: "passenger acquisition, loyalty, and a premium brand experience", offer: "Ride X can offer your passengers seamless first/last-mile rides to and from the airport, plus in-app co-branded loyalty rewards that drive repeat bookings.", ask: "an airport-transfer and loyalty co-marketing partnership" };
  if (s.includes("logistics") || s.includes("mobility") || s.includes("delivery"))
    return { interest: "delivery density, fleet utilization, and brand reach", offer: "Ride X's logistics and marketplace flows generate high parcel volume. A capacity-sharing or co-branded delivery partnership improves unit economics and coverage for both sides.", ask: "a delivery-capacity and co-branded mobility partnership" };
  if (s.includes("tech") || s.includes("software") || s.includes("artificial intelligence") || s.includes("semiconductor") || s.includes("it ") || s.includes("networking") || s.includes("crypto"))
    return { interest: "developer reach, platform adoption, and integration partnerships", offer: "Ride X is a high-traffic consumer platform open to API integrations — from payments and AI assistants to cloud and developer tooling — giving your product distribution to a large African user base.", ask: "a platform-integration and co-marketing partnership" };
  if (s.includes("media") || s.includes("entertainment") || s.includes("streaming") || s.includes("gaming"))
    return { interest: "audience growth, content distribution, and advertising monetization", offer: "Ride X's in-app audience and ad inventory can distribute and monetize your content and titles, while cross-promotion drives subscriptions and watch time.", ask: "a content-distribution and cross-promotion partnership" };
  if (s.includes("found") || s.includes("government") || s.includes("csr"))
    return { interest: "youth empowerment, job creation, and measurable social impact", offer: "Ride X's driver, courier, and creator-economy livelihoods align with your empowerment mandate. A co-funded program can create jobs and deliver auditable impact metrics.", ask: "a co-funded empowerment and impact partnership" };
  if (s.includes("consult") || s.includes("hr"))
    return { interest: "advisory engagement and client introductions", offer: "Ride X's rapid growth across mobility, logistics, media, and fintech creates ongoing need for strategy, audit, and talent services — a strong reference client in African tech.", ask: "an advisory and retainer engagement" };
  if (s.includes("apparel") || s.includes("luxury") || s.includes("conglomerate") || s.includes("manufactur") || s.includes("steel") || s.includes("chemical"))
    return { interest: "brand prestige, consumer reach, and product placement", offer: "Ride X's lifestyle audience and sponsored placements offer premium visibility and product placement across ride, event, and entertainment touchpoints.", ask: "a brand-ambassador and sponsored-placement partnership" };
  return { interest: "growth, brand reach, and measurable ROI", offer: "Ride X is an all-in-one lifestyle platform — rides, delivery, equipment rental, entertainment, music, live sports, and media — reaching a large, high-intent African consumer base that aligns with your growth goals.", ask: "a strategic partnership or sponsorship" };
}

// Build a tailored proposal letter on-device (zero credits / no API).
export function generateProposal(company, sender = {}) {
  const a = sectorAngle(company.sector);
  const you = sender.name || "Ride X Partnerships";
  const email = sender.email || "partnerships@ridex.app";
  const phone = sender.phone ? ` or ${sender.phone}` : "";
  const date = new Date().toLocaleDateString();
  return `Date: ${date}

To: Partnerships / Business Development
${company.name}
Sector: ${company.sector}
Website: ${company.website}

Subject: Partnership Proposal — Ride X × ${company.name}

Dear ${company.name} Team,

I am ${you}, reaching out from Ride X — an all-in-one lifestyle super-app spanning ride-hailing, logistics, equipment rental, car wash, entertainment, music, live sports, and media across Africa.

We see that ${company.name} cares deeply about ${a.interest}. Ride X is built to serve exactly that:

${a.offer}

We would love to explore ${a.ask} with ${company.name}. We are ready to move quickly and can tailor scope, commercial terms, and reporting to your priorities.

I would welcome a short call to share numbers and a draft term sheet. Reach me at ${email}${phone}.

Thank you for your time and consideration.

Warm regards,
${you}
Ride X Partnerships
${email}${phone ? ` · ${sender.phone}` : ""}
${company.website}`;
}